### PR TITLE
Adds special treatment for ctags also for virtual builds

### PR DESCRIPTION
**Pull request by noseglasses**
Copied the ctags settings from avr/platform.txt

Signed-off-by: Florian Fleissner <florian.fleissner@inpartik.de>

### CODE REVIEW

**Comment by noseglasses** [comment]
Can anybody explain why Travis fails on this PR? Also, why does the above menu say "Files changed 0"?

**Comment by algernon** [comment]
Travis has been failing on the bundle repo for a good while now. I tried to figure out why a few months ago, but didn't get far, couldn't reproduce the same error.

For changed files, I  suppose merging master into your PR branch confused  the GitHub UI.

**Comment by algernon** [comment]
Oh. It says 0 files changed, because https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio/commit/7201f5a57daf71fa5867e9ca9a720050cb31281d - it's already in there? Came in via #23, which also added the sketch header/footer thing to the virtual platform, too.

So I guess this PR is not needed anymore?

**Comment by noseglasses** [comment]
Right. Thanks! Closing.

**Pull request closed without merging**
